---
- name: apply base config
  hosts: ios
  gather_facts: false

  tasks:
    # - name: execute base_config role
    #   include_role:
    #     name: base_config

    - name: configure vlan
      include_role:
        name: vlan_config

    # - name: execute bgp_config role
    #   include_role:
    #     name: bgp_config
    #   tags: test1
