---
- name: apply base config
  hosts: ios
  gather_facts: false

  tasks:
    - name: execute base_config role
      include_role:
        name: base_config

    - name: execute bgp_config role
      include_role:
        name: bgp_config
      vars:
        bgp_neighbor_ip: "{{ item }}"
      with_items:
        - 1.1.1.2
        - 1.1.1.3
