- name: Define Values From CSV File
  set_fact:
    int_description: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=1') }}"
    password: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=2') }}"
    phys_int_name: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=3') }}"
    phys_int_ip: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=4') }}"
    phys_int_mask: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=5') }}"
    loop_int_name: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=6') }}"
    loop_int_ip: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=7') }}"
    loop_int_mask: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=8') }}"
    local_as_id: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=9') }}"
    neighbor_ip: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=10') }}"
    remote_as_id: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=11') }}"
    neighbor_1_ip: "{{ lookup('csvfile', bgp_neighbor_ip+' file=mjdoc.csv delimiter=, col=12') }}"

- name: land the config
  ios_config:
    src: bgp_template.j2


###
