---
- name: configure lo interfaces
  ios_config:
    src: ifs_config.j2
  vars:
    phys_int_name: "{{loopback_ifs_name}}"
    int_description: "IOS DESCRIPTION"
    phys_int_ip: "{{loopback_ifs_ip}}"
    phys_int_mask: "{{loopback_ifs_netmask}}"
    loopback: True

- name: configure interfaces
  ios_config:
    src: ifs_config.j2
  vars:
    phys_int_name: "{{item.name}}"
    int_description: "IOS DESCRIPTION"
    phys_int_ip: "{{item.ip}}"
    phys_int_mask: "{{bgp_netmask}}"
    loopback: False
  with_items: "{{ifs_list}}"

- name: configure bgp
  ios_config:
    src: bgp_config.j2
  vars:
    local_as_id: "{{bgp_config.as}}"
    loop_int_ip: "{{loopback_ifs_ip}}"
    neighbor_ip: "{{hostvars[item.bgp_neighbor].loopback_ifs_ip}}"
    remote_as_id: "{{hostvars[item.bgp_neighbor].bgp_config.as}}"
    loop_int_name: "{{loopback_ifs_name}}"
    loop_int_mask: "{{loopback_ifs_netmask}}"
    neighbor_dict: "{{hostvars[item.bgp_neighbor].ifs_list | selectattr('bgp_neighbor', 'equalto', inventory_hostname) | first}}"
    neighbor_1_ip: "{{ neighbor_dict.ip}}"
  with_items: "{{ifs_list}}"
