---

- name: Setup VLANs
  include_tasks: vlan_config.yml
  with_items: "{{ vlans | default([]) }}"

- name: configure interfaces to trunk mode {{item.name}}
  ios_config:
    lines:
    - "switchport"
    - "switchport trunk encapsulation dot1q"
    - "switchport mode trunk"
    - "switchport trunk allowed vlan {{ item.trunk_vlans | join(',') }}"
    parents: "interface {{ item.name }}"
  with_items: "{{ ifs_list | default([])}}"

- ios_config:
    lines:
    - "ip address 10.{{inventory_hostname | replace('r', '') }}.{{item.id}}.1 255.255.255.0"
    parents: "interface vlan {{item.id}}"
  with_items: "{{vlans}}"


#sw trunk allowed  vlan 10,20,30,40
